services:
  postgres:
    image: postgres:latest
    container_name: postgres_fiber
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres
volumes:
  postgres_data:
